ImportarEexportar/Controllers/ExportarController.cs
using ClosedXML.Excel;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Data;
using System.Data.SqlClient;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ImportarEexportar.Controllers
{
    public class ExportarController : Controller
    {
        private SqlConnection _osqlconnection;

        // GET: Exportar
        public ActionResult Export()
        {
            return View();
        }
        public ActionResult Exportarxls(string Nome)
        {
            try
            {
                _osqlconnection = new SqlConnection(ConfigurationManager.ConnectionStrings["EscolaConnectionString"].ConnectionString);

                DataTable dt = new DataTable();
                SqlCommand cmd = new SqlCommand();
                SqlDataAdapter da = new SqlDataAdapter();


                cmd = new SqlCommand("[dbo].[DadosAlunos]", _osqlconnection);

                cmd.Parameters.Add("@Nome", SqlDbType.VarChar).Value = Nome;

                cmd.CommandType = CommandType.StoredProcedure;

                da.SelectCommand = cmd;

                da.Fill(dt);
                if(dt.Rows.Count > 0)
                {
                    dt.TableName = "Dados_Do_Aluno";
                    using (XLWorkbook wp = new XLWorkbook())
                    {
                        wp.Worksheets.Add(dt);
                        wp.Style.Alignment.Horizontal = XLAlignmentHorizontalValues.Center;
                        wp.Style.Font.Bold = true;
                        Response.Clear();
                        Response.Buffer = true;
                        Response.Charset = "";
                        Response.ContentType = "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet";
                        Response.AddHeader("content-disposition", "attachment; filename=TabelaAlunos.xlsx");
                        using(MemoryStream MyMemoryStream = new MemoryStream())
                        {
                            wp.SaveAs(MyMemoryStream);
                            MyMemoryStream.WriteTo(Response.OutputStream);
                            Response.Flush();
                            Response.End();
                        }
                    }
                }else if(dt.Rows.Count <= 0)
                {
                    ViewBag.Mensagem = "Não existem dados a serem exportados";
                }
                return View();

            }
            catch(Exception ex)
            {
                ViewBag.Mensagem = "Erro: " + ex.Message + "" + ex.InnerException;
                return View();
            }
        }
    }
}

ImportarEexportar/Views/Exportar/Export.cshtml
@{
    ViewBag.Title = "Export";
}

<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Importar Xls</title>

    @Scripts.Render("~/Scripts/importxls.js")

</head>
<body>
    <div class="row">
        <h2 style="margin-left:30px;">Exportar Dados do Aluno atráves do Excel</h2>
        <div class="col-md-12">
            @Html.Partial("_Menu1")
            <br />
        </div>
        <div class="col-md-12">
            <form style="margin-left:15px;" method="post" action="~/Exportar/Exportarxls">
                <h5>
                    Informe o Nome do Aluno:
                </h5>
                <input type="text" name="Nome" />
                <button class="btn btn-danger" type="submit" name="export">Exportar Dados</button>
            </form>
        </div>
    </div>

</body>
</html>

ImportarEexportar/Views/Exportar/Exportarxls.cshtml
@{
    ViewBag.Title = "Exportarxls";
}
<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Importar Xls</title>

    @Scripts.Render("~/Scripts/importxls.js")

</head>
<body>
    <div style="color:red;">
        <h4>@ViewBag.Mensagem</h4>
    </div>
    <li class="btn btn-danger" style="text-decoration:none;"><a style="color:white; text-decoration:none;" href="@Url.Action("Export","Exportar")">Voltar</a></li>
</body>
</html>